image: facio/dynein_walk

build:
  stage: build
  script:
    - pwd
    - make
    - pwd
    - make clean
    - make
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - echo I already built everything...
    - ls -lh public
  artifacts:
    paths:
      - public
