build:
  stage: build
  before_script:
    - apt-get update -qq
    - apt-get install -y inkscape
    - apt-get install -y texlive texlive-xetex texlive-latex-extra python-matplotlib # for papers
    - git config --global user.email "testing-on-travis@example.com"
    - git config --global user.name "Travis Builder"
  script:
    - make
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  before_script:
    - apt-get update -qq
    - apt-get install -y inkscape
    - apt-get install -y texlive texlive-xetex texlive-latex-extra python-matplotlib # for papers
    - git config --global user.email "testing-on-travis@example.com"
    - git config --global user.name "Travis Builder"
  script:
    - make
  artifacts:
    paths:
      - public
