image: facio/dynein_walk

build:
  stage: build
  script:
    - cd reorganize && make
    - cd reorganize && make clean
    - cd reorganize && make
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - echo I already built everything...
    - rm -rf public
    - mv reorganize/public public
    - ls -lh public/
  artifacts:
    paths:
      - public
