dist: trusty
sudo: required

language: c++
compiler:
  - gcc
  - clang

script:
  - $CXX --version
  - make
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y inkscape
  - sudo apt-get install -y texlive-full # for papers
  - git config --global user.email "testing-on-travis@example.com"
  - git config --global user.name "Travis Builder"
